[package]
name = "rustdocissue"
version = "0.1.0"
authors = ["Joshua Groves <josh@joshgroves.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx-backend-empty = "0.5"
